# Generated by Django 5.2.15 on 2026-06-30 12:58

import django.db.models.deletion
import django.db.models.functions.datetime
import personas.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.UUIDField(db_default=personas.functions.GenRandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('tipo', models.TextField(choices=[('hospital', 'Hospital'), ('clinica', 'Clínica'), ('organizacion', 'Organización'), ('oficial', 'Ente oficial'), ('partner', 'Partner (Cruz Roja / Prot. Civil)')], default='hospital')),
                ('zona', models.TextField(blank=True, help_text='Ciudad/estado de referencia', null=True)),
                ('verificada', models.BooleanField(default=False, help_text='Solo admins pueden marcar verificada. Desbloquea acciones sensibles (registrar fallecido, etc.).')),
                ('activa', models.BooleanField(default=True)),
                ('dominio_email', models.TextField(blank=True, help_text='Dominio institucional (p.ej. hvargas.gob.ve) para auto-verificar responders.', null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.UUIDField(db_default=personas.functions.GenRandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('rol', models.TextField(choices=[('miembro', 'Miembro'), ('admin', 'Admin de workspace')], default='miembro')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responders', to='instituciones.institucion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'responders',
            },
        ),
    ]
