# Generated by Django 5.2.15 on 2026-06-28 07:25

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
import personas.functions
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFuente',
            fields=[
                ('id', models.UUIDField(db_default=personas.functions.GenRandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('tipo', models.TextField(help_text="'buscado' | 'encontrado'")),
                ('identificado', models.BooleanField(db_default=models.Value(True), help_text='false = encontrado sin identificar')),
                ('fuente', models.TextField(help_text="'dtv' | 'vtb' | 'venapp' | 'hospital_vargas' | 'ig_*'")),
                ('id_origen', models.TextField(blank=True, null=True)),
                ('url_origen', models.TextField(blank=True, help_text='link de vuelta para verificar', null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('nombre_norm', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Lower(personas.functions.ImmutableUnaccent(personas.functions.RegexpReplace(django.db.models.functions.comparison.Coalesce('nombre', models.Value('')), models.Value('\\s+'), models.Value(' '), models.Value('g')))), output_field=models.TextField())),
                ('cedula', models.TextField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.TextField(blank=True, null=True)),
                ('zona', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='ropa, tatuajes, cicatrices, rasgos', null=True)),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('foto_phash', models.TextField(blank=True, help_text='perceptual hash: detecta MISMA foto', null=True)),
                ('face_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, help_text='InsightFace: detecta MISMA persona en otra foto', null=True)),
                ('estado_rep', models.TextField(blank=True, help_text='sin_contacto | encontrado_vivo | herido | fallecido', null=True)),
                ('ubicacion', models.TextField(blank=True, help_text='hospital/centro donde está (si encontrado)', null=True)),
                ('contacto', models.TextField(blank=True, null=True)),
                ('tipo_fuente', models.TextField(db_default=models.Value('familiar'), help_text='familiar | rescatista | hospital | oficial')),
                ('confianza', models.FloatField(db_default=models.Value(1.0), help_text='baja si vino de extracción LLM')),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'registros_fuente',
            },
        ),
        migrations.CreateModel(
            name='EstadoClaim',
            fields=[
                ('id', models.UUIDField(db_default=personas.functions.GenRandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('estado', models.TextField(help_text='sin_contacto | encontrado_vivo | herido | fallecido')),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('autor_tipo', models.TextField(blank=True, help_text='familiar | responder | oficial | sistema', null=True)),
                ('autor_id', models.UUIDField(blank=True, help_text='responder_id o registro_fuente que lo originó', null=True)),
                ('corrobora_a', models.UUIDField(blank=True, help_text='otro claim que confirma (p/ fallecido)', null=True)),
                ('vigente', models.BooleanField(db_default=models.Value(True), help_text='false = revertido/superado')),
                ('disputado', models.BooleanField(db_default=models.Value(False), help_text='la familia lo objetó')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'estado_claims',
            },
        ),
        migrations.CreateModel(
            name='ParNegativo',
            fields=[
                ('registro_a', models.ForeignKey(db_column='registro_a', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='personas.registrofuente')),
                ('registro_b', models.ForeignKey(db_column='registro_b', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='personas.registrofuente')),
                ('pk', models.CompositePrimaryKey('registro_a', 'registro_b', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pares_negativos',
            },
        ),
        migrations.CreateModel(
            name='PersonaCanonica',
            fields=[
                ('id', models.UUIDField(db_default=personas.functions.GenRandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('nombre_display', models.TextField(blank=True, null=True)),
                ('cedula', models.TextField(blank=True, null=True)),
                ('zona', models.TextField(blank=True, null=True)),
                ('estado_actual', models.TextField(blank=True, help_text='derivado del claim vigente más confiable', null=True)),
                ('foto_principal', models.TextField(blank=True, null=True)),
                ('n_fuentes', models.IntegerField(db_default=models.Value(1))),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'personas_canonicas',
            },
        ),
        migrations.CreateModel(
            name='ClusterLink',
            fields=[
                ('registro', models.OneToOneField(db_column='registro_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cluster_link', serialize=False, to='personas.registrofuente')),
                ('score', models.FloatField(blank=True, null=True)),
                ('metodo', models.TextField(blank=True, choices=[('cedula', 'cedula'), ('phash', 'phash'), ('fuzzy', 'fuzzy'), ('cara', 'cara'), ('llm', 'llm'), ('manual', 'manual'), ('usuario', 'usuario')], null=True)),
                ('confirmado', models.BooleanField(db_default=models.Value(False))),
            ],
            options={
                'db_table': 'cluster_links',
            },
        ),
        migrations.AddIndex(
            model_name='registrofuente',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nombre_norm'], name='idx_rf_nombre', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='registrofuente',
            index=models.Index(fields=['zona'], name='idx_rf_zona'),
        ),
        migrations.AddIndex(
            model_name='registrofuente',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['face_embedding'], m=16, name='idx_rf_face', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='registrofuente',
            constraint=models.UniqueConstraint(fields=('fuente', 'id_origen'), name='uniq_fuente_id_origen'),
        ),
        migrations.AddConstraint(
            model_name='registrofuente',
            constraint=models.UniqueConstraint(condition=models.Q(('cedula__isnull', False)), fields=('cedula',), name='idx_rf_cedula'),
        ),
        migrations.AddField(
            model_name='estadoclaim',
            name='persona',
            field=models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='personas.personacanonica'),
        ),
        migrations.AddField(
            model_name='clusterlink',
            name='persona',
            field=models.ForeignKey(blank=True, db_column='persona_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='personas.personacanonica'),
        ),
        migrations.AddIndex(
            model_name='estadoclaim',
            index=models.Index(fields=['persona', 'vigente'], name='idx_claims_persona'),
        ),
    ]
