# Generated by Django 5.2.15 on 2026-06-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_cedula_reconciliacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterlink',
            name='metodo',
            field=models.TextField(blank=True, choices=[('bootstrap', 'bootstrap'), ('cedula', 'cedula'), ('phash', 'phash'), ('fuzzy', 'fuzzy'), ('cara', 'cara'), ('llm', 'llm'), ('manual', 'manual'), ('usuario', 'usuario')], null=True),
        ),
    ]
