# Generated by Django 5.2.15 on 2026-06-30 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
        ('personas', '0004_cluster_link_bootstrap_metodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoclaim',
            name='autor_id',
        ),
        migrations.RemoveField(
            model_name='estadoclaim',
            name='corrobora_a',
        ),
        migrations.AddField(
            model_name='estadoclaim',
            name='autor_registro',
            field=models.ForeignKey(blank=True, db_column='autor_registro_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_autorados', to='personas.registrofuente'),
        ),
        migrations.AddField(
            model_name='estadoclaim',
            name='autor_responder',
            field=models.ForeignKey(blank=True, db_column='autor_responder_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='instituciones.responder'),
        ),
        migrations.AddField(
            model_name='estadoclaim',
            name='corrobora',
            field=models.ForeignKey(blank=True, db_column='corrobora_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corroborado_por', to='personas.estadoclaim'),
        ),
        migrations.AlterField(
            model_name='clusterlink',
            name='metodo',
            field=models.TextField(blank=True, choices=[('bootstrap', 'Bootstrap'), ('cedula', 'Cédula'), ('phash', 'pHash'), ('fuzzy', 'Fuzzy'), ('cara', 'Cara'), ('llm', 'LLM'), ('manual', 'Manual'), ('usuario', 'Usuario')], null=True),
        ),
        migrations.AlterField(
            model_name='estadoclaim',
            name='autor_tipo',
            field=models.TextField(blank=True, choices=[('familiar', 'Familiar'), ('responder', 'Responder'), ('oficial', 'Oficial'), ('sistema', 'Sistema')], null=True),
        ),
        migrations.AlterField(
            model_name='estadoclaim',
            name='estado',
            field=models.TextField(choices=[('sin_contacto', 'Sin contacto'), ('encontrado_vivo', 'Encontrado vivo'), ('herido', 'Herido'), ('hospitalizado', 'Hospitalizado'), ('refugiado', 'Refugiado'), ('fallecido', 'Fallecido')]),
        ),
        migrations.AlterField(
            model_name='personacanonica',
            name='cedula_confirmada_por',
            field=models.TextField(blank=True, choices=[('responder', 'Responder'), ('oficial', 'Oficial'), ('cne', 'CNE'), ('consenso', 'Consenso')], null=True),
        ),
        migrations.AlterField(
            model_name='personacanonica',
            name='cedula_estado',
            field=models.TextField(choices=[('confirmada', 'Confirmada'), ('conflicto', 'Conflicto'), ('sin_confirmar', 'Sin confirmar')], db_default=models.Value('sin_confirmar')),
        ),
        migrations.AlterField(
            model_name='personacanonica',
            name='estado_actual',
            field=models.TextField(blank=True, choices=[('sin_contacto', 'Sin contacto'), ('encontrado_vivo', 'Encontrado vivo'), ('herido', 'Herido'), ('hospitalizado', 'Hospitalizado'), ('refugiado', 'Refugiado'), ('fallecido', 'Fallecido')], help_text='derivado del claim vigente más confiable', null=True),
        ),
        migrations.AlterField(
            model_name='registrofuente',
            name='estado_rep',
            field=models.TextField(blank=True, choices=[('sin_contacto', 'Sin contacto'), ('encontrado_vivo', 'Encontrado vivo'), ('herido', 'Herido'), ('hospitalizado', 'Hospitalizado'), ('refugiado', 'Refugiado'), ('fallecido', 'Fallecido')], null=True),
        ),
        migrations.AlterField(
            model_name='registrofuente',
            name='tipo',
            field=models.TextField(choices=[('buscado', 'Buscado'), ('encontrado', 'Encontrado')]),
        ),
        migrations.AlterField(
            model_name='registrofuente',
            name='tipo_fuente',
            field=models.TextField(choices=[('familiar', 'Familiar'), ('rescatista', 'Rescatista'), ('hospital', 'Hospital'), ('clinica', 'Clínica'), ('oficial', 'Oficial'), ('partner', 'Partner')], db_default=models.Value('familiar')),
        ),
    ]
