# Generated by Django 5.2.15 on 2026-06-29 11:52

import django.db.models.functions.datetime
import personas.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(db_default=personas.functions.GenRandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('fuente', models.TextField(blank=True, help_text='Fuente ingerida (None = todas las del archivo)', null=True)),
                ('archivo', models.TextField(blank=True, help_text='Ruta al archivo JSON procesado', null=True)),
                ('iniciada_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('terminada_at', models.DateTimeField(blank=True, null=True)),
                ('leidos', models.IntegerField(default=0)),
                ('insertados', models.IntegerField(default=0)),
                ('actualizados', models.IntegerField(default=0)),
                ('sin_cambio', models.IntegerField(default=0)),
                ('omitidos', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ingesta_sync_runs',
                'ordering': ['-iniciada_at'],
            },
        ),
    ]
