# Generated by Django 5.2.15 on 2026-06-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0001_syncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='fallida',
            field=models.BooleanField(default=False),
        ),
    ]
